### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by AyudantesTecnicas** [pciruzzi/template-tp-grupal#1]
Tienen que definir cual va a ser su workflow en Git. Pueden dejarlo especificado en una página de la Wiki.

https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by pciruzzi** [comment]
Hecho [acá](https://github.com/pciruzzi/template-tp-grupal/wiki/Workflow)

**Comment by AyudantesTecnicas** [comment]
El repositorio no refleja las características que indica git-flow. Hagan los cambios correspondientes al repo o actualicen la pagina de la wiki

**Comment by pciruzzi** [comment]
Hola! Si te referís al hecho de no haber hecho el release sobre master, lo que sucedió es que según tenía entendido en master solo debe haber versiones beta, es decir, que tengan toda la funcionalidad, lo cual a la hora de hacer la entrega no estaba hecho (Ya que nos faltaba uno de los juegos). Es por ello que decidimos hacerlo sobre develop. Si es eso, no se como podemos modificar el tag para que a la hora de hacerlo esté todo en master (Creo que no se puede). Si no es eso, te pido si nos podes decir qué es así poder modificarlo!

Gracias.

**Comment by pciruzzi** [comment]
Tendremos en cuenta lo hablado por Slack para las siguientes entregas.
