### ISSUE TITLE
Mock definido entre las clases del modelo

### ISSUE THREAD

**Issue by agustincarames** [pciruzzi/template-tp-grupal#11]

**Comment by pciruzzi** [comment]
Dónde debería definirse? En un paquete aparte? O a qué se refieren en particular con esto?

**Comment by agustincarames** [comment]
Convencionalmente va entre los test, para que el sistema de build solo lo incluya al momento de testear. Si hace falta en otro momento, entonces no es un mock o estan mal distribuidas las responsabilidades de testeo.

**Comment by plandino** [comment]
Trate de hacerlo, y tenia que estar bien, pero rompe el findbugsmain por un tema de dependencias y los atributos protected cuando cambie las clases al paquete de test. Habría que desactivarlo para resolver este problema.

**Comment by agustincarames** [comment]
Para que se usa ese queue? Probe remover las variables asignadas y nunca leidas a medida que findbugs las encontraba y hasta donde vi quedan funcionando tanto los test como el despertar/enojar de El Escape 2

**Comment by pciruzzi** [comment]
Yo no fui el que intentó el cambio, pero la queue se utiliza para los mensajes asincrónicos, es decir, los del tiempo. Esto es así ya que a través de la interfaz del driver está definida la forma de que el que se encargue de "acolar" sea el "Interactor" que interactua con el cliente. Pero la diferencia es que en esos casos, la acción de acolar es debido a un sendCommand a través del driver. Como los mensajes del tiempo no suceden a través de un sendCommand, lo que se hizo es que directamente sea posible "acolar" mensajes sólo del tipo broadcast (A través de la interfaz BroadcastQueue) directamente desde el modelo (lease, engine, etc).

**Comment by agustincarames** [comment]
Eso suena suficientemente importante que es raro que solo se llame de un mock de una clase que en si no lo usa. Puede que haya quedado algo a medio implementar o sea un mecanismo duplicado?

**Comment by plandino** [comment]
Ya lo solucione, habían quedado cosas demás que no eran necesarias y por eso rompía el findbugs.
