### ISSUE TITLE
Hay partes del codigo que no se sabe si estan completas

### ISSUE THREAD

**Issue by agustincarames** [pciruzzi/template-tp-grupal#12]
Hay codigo comentado, codigo con TODO pidiendo borrarlo o revisarlo. Al menos parte de esto es claramente codigo insertado para ahorrar pasos al testear a mano

**Comment by pciruzzi** [comment]
Yo hice la revisión final y me olvidé de pasar a través de los TODO's que habíamos dejado a lo largo del TP. Como bien dijiste, la mayoría son para testear más fácilmente a mano. Los sacamos...

**Comment by petaalcala** [comment]
Codigo comentado borrado al igual que los TODOs
