### ISSUE TITLE
Tests de la entrega 3

### ISSUE THREAD

**Issue by agustincarames** [pciruzzi/template-tp-grupal#13]
El proposito de estos test es verificar que el juego funciona correctamente en casos que hay esperas o comportamiento aleatorio, sin las complicaciones que causa tener tiempos innecesariamente grandes de ejecucion o fallos aleatorios en tests.
Actualmente, verifican unicamente que el juego puede recibir eventos temporales.

**Comment by pciruzzi** [comment]
Realizamos los tests que pidieron para verificar la tercer entrega. Qué otros tests deberíamos realizar ahora? Porque justamente testea el tema de las nuevas condiciones de pérdida, más allá de las anteriores (Bajar sin el martillo, etc)

**Comment by agustincarames** [comment]
Principalmente, la idea de validad esos circuitos es que el juego realice esas cosas, no que uno fuerce el comportamiento desde los test.
En particular, con startMockedAction saltean toda la parte que corresponde a iniciar los eventos temporales, y de MoveRandom solo se verifica que el constructor no lanza excepcion.

Si miran los reportes de jacoco (task jacocoTestReport), eso es bastante mas visible.

**Comment by petaalcala** [comment]
Perdón pero no entiendo lo que se plantea. Los tests pedidos de la tercer
entrega están. No entiendo que otras cosas habría que testear.
Los ICommands si no me equivoco están testeados, que otra cosa quedaría por
testear?.

**Comment by agustincarames** [comment]
(Por las dudas: Con este issue refiero especificamente a los dos test que se pidieron como actividad durante la entrega. El resto de los test estan bien!)

El problema no es que falten test, es que no llegan a ser de aceptacion: en los test siguen los mismos pasos iniciales dentro del juego que en El Escape 1, pero al momento de pasar por partes mas complejas descarrilan completamente, fuerzan al juego a pasar por caminos que no sigue en una ejecucion normal, y en eso no se verifican caminos que si se usan.
Aunque haya partes que deban mockear por ser hostiles al testeo automatizado, hacer un mock mas amplio de lo necesario les deja comportamiento critico sin testear (vease: entregar con el codigo relacionado al licor comentado). 
Busquen como reducir esta area "intesteable", que es bastante mas chica de lo que parece!

**Comment by plandino** [comment]
Hola, no estamos entendiendo cual es el problema que mencionas. Creemos que es algo relacionado con los mocks, pero no sabemos bien cual es problema.

Estas diciendo que forzamos el test o que no pasamos por los caminos normales, cuando lo único que teníbamos que hacer para la entrega y que lo hicimos, fueron los tests que ustedes nos entregaron.
Para hacer esos tests mockeamos la acción de que el bibliotecario se mueva después de cierto tiempo de quedarse dormido y que haga perder a tal jugador y no al otro, porque es al que se encuentra. El objetivo de los tests es ese, no probar como se pasa la Foto a la Credencial.
Para lograr eso tuvimos que hacer los mocks que modifican el estado del juego, como tendría que ser.

Por favor podes ser más claro y preciso con lo que queres que hagamos, porque no estamos entendiendo.

**Comment by agustincarames** [comment]
Ok, buscando en el material no lo encuentro, pero la palabra clave es aceptacion: Una vez inicializado el sistema en prueba, se usan unicamente las interacciones y observaciones que puede tener un usuario con su sistema desde el cliente. Esta es la forma clara y precisa.

Desde un punto menos textual y mas didactico: apuntamos con esto a que tengan que hacer tests sobre cosas que explicitamente usan tiempo y random, dos cosas que usualmente dificultan debuggear y testear. Mockear todos los componentes que siquiera refieren a esos conceptos resulta en que se escapen bugs en las implementaciones reales.

**Comment by pciruzzi** [comment]
A ver si comprendo, la idea que planteas es la de que el hecho de "activarse" que el tiempo pasó y demás no debería formar parte del test, sino que debería ser algo que nosotros a través de la interfaz de la clase (en este caso el engine y su método doCommand) deberíamos hacer que suceda, en vez de hacer "despertar.startMockedAction()". O estoy entendiendo mal?

**Comment by agustincarames** [comment]
Estas entendiendo bien, si. Nomas que para no cambiar lo que puede hacer el usuario en el sistema real, el comando para adelantar el tiempo deberia estar expuesto unicamente al thread que actualiza el tiempo y a los test.

**Comment by plandino** [comment]
Ya esta solucionado, avísanos si te parece bien así o le tenemos que cambiar algo mas.

**Comment by agustincarames** [comment]
Faltaria hacer exactamente lo mismo al mock de random (el caso forzado ahora es MoveRandom::setDestinationElement, que saltea la logica de seleccion de habitaciones)

**Comment by petaalcala** [comment]
Te hago una pregunta Agustín.
Tratando de solucionar el tema este del mock del random, yo llegue a una solución que pasa los tests pero no se si es correcta. Esta en un branch aparte que abrí hoy.
Lo que hago es hacer un MockMoveRandom que adentro busca la habitación que yo le paso por parámetro. Quiero saber si esto esta bien hecho para mergearlo a develop y cerrar el Issue.
En el caso de que la idea sea Mockear el Random de Java como se hizo con el Timer, no encuentro una solución "directa" porque la diferencia aca es que el Random solo devuelve números de un rango determinado, y yo lo que busco el es el nombre de una habitación.
La única solución seria encapsular la selección de la habitación en una clase aparte, por ejemplo, con el mismo nombre Random pero propia, que yo le pase una lista de habitaciones y elija una.
Entonces lo que se haría luego seria mockear esa clase Random propia, que en vez de utilizar el random de java, utilice un string que paso por parametro y devuelva esa habitación si es que existe.
Se entiende la diferencia?

**Comment by agustincarames** [comment]
Entre esas opciones, te diria que tomes la ultima (una clase que decide como hacer la seleccion aleatoria), porque es la que reemplaza la menor cantidad de cosas por un mock.

**Comment by petaalcala** [comment]
Perfecto. Justamente lo charle con los chicos y estoy en eso.

**Comment by petaalcala** [comment]
Solucionado.
