### ISSUE TITLE
Agregar produccion de jar a build.gradle

### ISSUE THREAD

**Issue by agustincarames** [pciruzzi/template-tp-grupal#16]
Como mencionan en la documentacion que no lo encontraron:
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html
https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:adding_dependencies_to_tasks

**Comment by pciruzzi** [comment]
Esto lo pregunté yo en particular para antes de la 2da entrega y me dijeron que no importaba cómo se obtenían los jars, siempre que se hicieran; por eso decidimos dejarlo así.

**Comment by pciruzzi** [comment]
Hola, recién estuve intentando hacerlo. Hice el siguiente archivo jars.gradle, ubicado en la carpeta gradle del tp:
`//create multiple jars`
`task jars(type: Exec) {`
        `commandLine './all.sh'`
`}`

Pero no logro hacer que se ejecute cuando se llama a `gradle build` o `./gradlew build`, ya que no encontré en ningún archivo que se hiciera referencia a llamadas a los tasks de `:compileJava` o `:test` o de cualquier tipo, de forma de poder ejecutar este nuevo task luego de compilar. Estoy buscando hace rato y no logro nada. Alguna idea?

**Comment by agustincarames** [comment]
Podes agregar dependencias sin tocar la definicion de un task haciendo
`dependant.dependsOn dependency`

**Comment by pciruzzi** [comment]
Gracias!
