### ISSUE TITLE
Diferencia entre ICommand y ITimeCommand

### ISSUE THREAD

**Issue by agustincarames** [pciruzzi/template-tp-grupal#19]
Actualmente, para darle un ITimeCommand como accion al player, o un ICommand como accion temporal, necesitaria duplicarlos en la otra jerarquia. Hay alguna razon por la que esto es asi, o pueden unificarse los conceptos?

**Comment by plandino** [comment]
Ya esta comentado en la Wiki la razón de esta diferencia, luego de charlarlo con el ayudante.
