### ISSUE TITLE
Redundancia entre IInterpreter::interpret() e interpret(Player)

### ISSUE THREAD

**Issue by agustincarames** [pciruzzi/template-tp-grupal#22]
Las invocaciones a estos metodos, fuera del package de interpretes, son de la forma `x.interpret() || x.interpret(player)`. Dentro del package, hay versiones composite que delegan al interpret de algun objeto contenido, o nodos hoja con implementaciones similares, en muchos casos difiriendo unicamente en si usan un objeto contenido o un player.
Eliminen esta redundancia o aclaren por que son necesarios ambos metodos en cada interprete.

**Comment by plandino** [comment]
Esto es necesario ya que algunas condiciones para, por ejemplo abrir una puerta, ganar o perder el juego pueden implicar a un player o no. Por eso hay veces que a la acción de verificar la condición, se tiene que realizar sobre el mismo elemento que le pasaron (es el caso en que no se le pasa el player) o necesita que le pasen el player especifico que ejecutó la acción. 
Esto viene de la mano del player genérico. El player genérico se usa para no generar condiciones repetidas para todos los players al crear la configuración. Lo que se hace es pasarlo una vez a todas las condiciones y que luego al interpreter le pase el player real, de forma que chequee de verdad si el player que ejecutó la acción tiene la llave para abrir la puerta por ejemplo.

**Comment by agustincarames** [comment]
Entonces: se usa lo que se paso en el constructor, salvo que haya sido el player generico, que indica que se verifique sobre el player argumento.

[Hay una clase estandar para eso](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html)
