### ISSUE TITLE
Tests dependen de juegos

### ISSUE THREAD

**Issue by agustincarames** [pciruzzi/template-tp-grupal#7]
Los test de ICommand y del driver hacen uso de juegos concretos, por lo que necesitarian cambios si se modifican los juegos. Eliminar esta dependencia.

**Comment by pciruzzi** [comment]
Hola, los tests del Driver no veo la posibilidad de no utilizar un juego, ya que para utilizar el driver se necesita llamar al initGame si o si, sin eso no es posible testear mucho del mismo. O no? Gracias.

**Comment by agustincarames** [comment]
Para testear el driver necesitas algun juego, si, pero hacer que los test dependan de juegos especificos que el cliente pidio te va a causar fails innecesarios si alguna vez los quiere cambiar.

**Comment by franguerini** [comment]
Solucionado este issue con la configuracion de un juego dummy para poder testear ICommands
