### ISSUE TITLE
MoveWithComparator es especifica a Hanoi

### ISSUE THREAD

**Issue by agustincarames** [pciruzzi/template-tp-grupal#8]
MoveWithComparator es un comando del engine que codea la logica de los discos, y obliga a los builders que lo usan a definir logica de juego.

**Comment by plandino** [comment]
MoveWithComparator es un comando que sirve para mas que solo la lógica de los discos, sirve para cualquier caso que quieras mover una cosa de un lado a otro, revisando una cierta condición de tamaño. Por ejemplo que quisiéramos poner un libro arriba de una pila de libros para generar peso sobre un accionador y que se abra una puerta, pero solo se pueda poner un libro mas chico que el que esta arriba de la pila.
Y lo que de que los builders definan esa lógica es la idea del trabajo practico, que todo se pueda configurar, por si se quiere cambiar que en vez de ser en orden descendiente sea en orden ascendente.

**Comment by AyudantesTecnicas** [comment]
La forma en que la accion codea logica especifica es la contraria: Por que solo mover, y solo por tamaño ascendiente/descendiente/constante?

La idea del builder era que la configuracion eventualmente venga de alguna serializacion. Eso se dificulta si usas funciones anonimas

**Comment by plandino** [comment]
En realidad se puede usar cualquier lógica, ya que esa es la idea de pasarle el comparador. En vez de hacer un getSize() podes ponerle lo que quieras. Lo de la serializacion nunca se pidió al final.

Si de todas formas queres que lo arreglemos, lo que se nos ocurrió para evitar esto es que el MoveWithComparator pase a llamarse MoveSmallest y que tenga el comparador adentro del método, pero pasaría de ser un método genérico a algo mas especifico, que es lo que no querían.

**Comment by agustincarames** [comment]
Esto probablemente deberia desdoblarlo en dos issues, pero:
- MoveWithComparator es Move, pero con una condicion verificada antes de ejecutar. Esto tambien sucede en MovePlayerTo, pero sin una variante incondicional. La forma mas generica seria abstraer esta idea de una verificacion antes de ejecutar
- Esa logica que podes poner es codigo ejecutable de Java, planteado para algun juego y actuando desde dentro de tu modelo. Es lo que pedimos que no haya en los builders. Ya tienen otro mecanismo de condiciones implementado, que cumple con esto e incluso esta usado en MovePlayerTo

**Comment by petaalcala** [comment]
El problema que estamos teniendo es que MoveWithComparator y Move a secas
son cosas diferentes.
El MoveWithComparator recibe dos elementos que son pilas o cosas que
contienen cosas, que por si mismos no son nada digamos... no te interesa
mover la pilax a la pilaz, sino lo que está adentro de la pilax a la pilaz.
En cambio en el move, recibe el elemento concreto a mover y el contenedor.
Esto está hecho así de entrada, porque en los test y cosas de la primer
iteración, se pedía que los comandos sean "move top stackx stacky"',
entonces esos eran los objetos que íbamos a buscar en nuestro modelo.

**Comment by agustincarames** [comment]
Entonces esta bien, esa es una buena razon para mantener MoveWithComparator separado de Move.
