### ISSUE TITLE
Poison es especifico a Treasure Quest

### ISSUE THREAD

**Issue by agustincarames** [pciruzzi/template-tp-grupal#9]
El envenenamiento agrega logica no configurable a su sistema, como IsPoisoned, los chequeos en MoveToPlayer, el campo en Element.

**Comment by petaalcala** [comment]
Lo arreglamos teniendo una clase State, que tiene la lógica para devolver un determinado mensaje segun corresponda cuando ocurre determinado cambio de estado en el objeto.
Estos objetos se guardan en un Map que tiene la clase Element. Antes era solo un booleano para checkear este estado por ejemplo, actualmente hay un map que tiene los posibles estados del elemento y si ese estado es positivo o negativo.
